config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root to: "pages#home" -> besoin de ne pas nester pour pouvoir avoir ma page "new recommendation"
  # resources :communities, only: [:index, :show, :new, :create, :destroy] do
  #   resources :recommendations do
  #     resources :ratings, only: [:create]
  #   end
  # end

  root to: "pages#home"
  resources :communities do
    resources :recommendations
    resources :memberships, only: [:index, :new, :create, :destroy]
  end

  resources :recommendations, only: [:show] do
    resources :ratings, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :recommendations, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :name, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates :status, inclusion: { in: %w[accepted rejected pending] }
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :recommendation

  validates :score, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 6 }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_many :ratings, dependent: :destroy

  validates :category, inclusion: { in: %w[restaurant watch read podcast health shop trip] }
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :communities, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :communities, through: :memberships

  validates :email, :password, :username, presence: true
  validates :password, length: { minimum: 7 }
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[show edit update destroy]

  def index
    @communities = Community.where(user_id: current_user)
  end

  def show
    @recommendations = Recommendation.where(community_id: @community.id)
    @memberships = Membership.where(community_id: @community.id)
    @recommendation = Recommendation.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    @community.user = current_user
    if @community.save
      redirect_to community_path(@community)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @community = Community.find(params[:id])
    @community.update(community_params)
    if @community.save
      redirect_to community_path(@community)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @community.destroy
    redirect_to communities_path, notice: "Community deleted!"
  end

  private

  def community_params
    params.require(:community).permit(:name, :photo)
  end

  def set_community
    @community = Community.find(params[:id])
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def new
    @community = Community.find(params[:community_id])
    membership_user_id = Membership.where(community_id: @community.id).map { |mb| mb.user_id }
    @membership_users = User.where.not(id: current_user.id).where.not(id: membership_user_id)
    @membership = Membership.new
  end

  def create
    @community = Community.find(params[:community_id])
    @membership = Membership.new(membership_params)
    @membership.community = @community
    @membership.status = "pending"
    if @membership.save
      redirect_to community_path(@community), notice: "Member added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def membership_params
    params.require(:membership).permit(:user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @rating = Rating.new(rating_params)
    @rating.user = current_user
    @recommendation = Recommendation.find(params[:recommendation_id])
    @rating.recommendation = @recommendation
    if @rating.save
      redirect_to recommendation_path(@recommendation)
    else
      render "recommendations/show", status: :unprocessable_entity
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:score, :comment)
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_community, only: %i[new create]

  def index
    @recommendations = Recommendation.where(community_id: @community.id)
  end

  def show
    @recommendation = Recommendation.find(params[:id])
    @ratings = Rating.where(recommendation_id: @recommendation.id)
    @community = Community.find(@recommendation.community.id)
    @rating = Rating.new
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.community = @community
    @recommendation.user = User.first #current_user
    if @recommendation.save
      redirect_to community_recommendations_path(@community)
    else
      render :new, status: :unprocessable_entity, notice: "didn't work"
    end
  end

  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  def update
    @recommendation.update(recommendation_params)
    redirect_to recommendations_path, notice: "Recommendation modified !"
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
    redirect_to recommendations_path, notice: "Recommendation deleted!"
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def recommendation_params
    params.require(:recommendation).permit(:category, :title, :description, :address, :photo)
  end
end

app/controllers/recommentions_controller.rb
class RecommentionsController < ApplicationController
  def index
    @recommendations = Recommendation.all
  end

  def show
    @recommendation = Recommendation.find(params[:id])
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)
    if @recommendation.save
      redirect_to recommendation_path(@recommendation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  def update
    @recommendation.update(recommendation_params)
    redirect_to recommendations_path, notice: "Recommendation modified !"
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
    redirect_to recommendations_path, notice: "Recommendation deleted!"
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:category, :title, :description, :address, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icons_helper.rb
module IconsHelper
  def find_icon(category)
    case category
    when 'restaurant'
      'fa-utensils'
    when 'watch'
      'fa-video'
    when 'read'
      'fa-book-open'
    when 'podcast'
      'fa-microphone'
    when 'health'
      'fa-house-medical'
    when 'shop'
      'fa-cart-shopping'
    when 'trip'
      'fa-earth-americas'
    end
  end
end

app/views/communities/_form.html.erb
<div class="container">
  <%= simple_form_for @community do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.submit "Create a new community", class: "btn-grad" %>
   <% end %>
</div>

app/views/communities/edit.html.erb
<div class="container">
  <h1>Edit <%=@community.name%></h1>
  <%= link_to "Back to all the communities", communities_path %>

  <%= render "form"%>
</div>

app/views/communities/index.html.erb
<div class="container">
  <div class="title-community">
    <h1>All the communities of the current user</h1>
    <div class="btn-grad">
      <%= link_to "Create a new community", new_community_path %>
    </div>
  </div>


  <% @communities.each do |community| %>
    <%= link_to community_path(community) do %>
      <div class="card-community">
        <img src="<%=community.photo%>" alt="photo of a group of friend">
        <h3><%= community.name %></h3>
          <ul class="menu">
            <% community.memberships.first(5).each do |membership| %>
              <li>
                <div class="avatar">
                  <img src="<%= membership.user.avatar %>" alt="profil picture">
                </div>
              </li>
            <% end %>
            <li> + <%=community.memberships.count - 5 %> </li>
          </ul>
          </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/communities/new.html.erb
<div class="container">
  <h1>Create a new community</h1>
  <%= link_to "Back to all the communities", communities_path %>

  <%= render "form"%>
</div>

app/views/communities/show.html.erb
<div class="container">
  <%= link_to "Go back to all the communities", communities_path %>

  <h1><%=@community.name%></h1>
  <img src="<%=@community.photo%>" alt="photo of a group of friend">
  <%= link_to "Delete", @community, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%= link_to "Edit", edit_community_path(@community) %>

  <%= render "memberships/index"%>

  <%= render "recommendations/index"%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WouldRecommend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/memberships/_index.html.erb
<div class="container">
  <h1>Membership index</h1>
  <%= link_to "Add a new member", new_community_membership_path(@community) %>
  <ul><% @memberships.each do |membership| %>
    <li>
      <div class="avatar">
        <img src="<%= membership.user.avatar %>" alt="profil picture">
      </div>
      <p><%= membership.user.username %> </p>
    </li>
    <% end %>
  </ul>
</div>

app/views/memberships/new.html.erb
<div class="container">
  <h1>Add a new member to the community</h1>
  <%= simple_form_for [@community, @membership] do |f| %>
    <%= f.input :user_id, prompt: "Choose among the users", collection: @membership_users.map{ |user| [user.id, user.username] }, label_method: :second, value_method: :first %>
    <%= f.submit "Add this member" %>
  <% end %>

  <ul><% @membership_users.each do |mb_user| %>
    <li>
      <div class="avatar">
        <img src="<%=mb_user.avatar%>" alt="profil picture">
      </div>
      <p><%= mb_user.username %> - <%= mb_user.id %> </p>
    </li>
      <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="scroll1">
    <h1>Looking for a <span style="color: #FA7E0A">doctor</span> ?</h1>
    <h1>Let's check if your friends have any <span style="color: #FA7E0A">recommendations</span> for you.</h1>
    <img src="../assets/images/loupe.png" alt="femme avec loupe">
      <div class="btn-grad">
        <%= link_to "Get started", communities_path %>
      </div>
  </div>
  <div class="scroll2">
    <h1 style="color: #FA7E0A">Step 1</h1>
    <p>Join or create a community with your friends!</p>
  </div>
  <div class="scroll2">
    <h1 style="color: #FA7E0A">Step 2</h1>
    <p>Share your recommendations with each other!</p>
  </div>
  <div class="scroll3">
    <h1 style="color: #FA7E0A">Step 3</h1>
    <p>Enjoy!</p>
  </div>
</div>

app/views/ratings/_index.html.erb
<div class="container">
  <ul><% @ratings.each do |rating| %>
    <li><%= rating.score %> stars - <%= rating.comment %></li>
    <% end %>
  </ul>

  <%= simple_form_for [@recommendation, @rating] do |f| %>
    <%= f.input :score %>
    <%= f.input :comment %>
    <%= f.submit "Post", class: "btn-grad" %>
  <% end %>
</div>

app/views/recommendations/_form.html.erb
<div class="container">
  <%= simple_form_for [@community, @recommendation] do |f| %>
    <%= f.input :category, collection: %w[restaurant watch read podcast health shop trip] %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.submit "Create recommendation", class: "btn-grad" %>
   <% end %>
</div>

app/views/recommendations/_index.html.erb
<div class="container">
  <h1>Recommendations index</h1>

  <!-- Button trigger modal -->
  <button type="button" class="btn-grad" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add a recommendation
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New recommendation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container">
            <%= simple_form_for [@community, @recommendation] do |f| %>
              <%= f.input :category, collection: %w[restaurant watch read podcast health shop trip] %>
              <%= f.input :title %>
              <%= f.input :description %>
              <%= f.submit "Create recommendation", class: "btn-grad" %>
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button> %>
        </div>
      </div>
    </div>
  </div>

  <div class="recommendations-list">
    <% @recommendations.each do |recommendation| %>
      <div class="card-recommendation <%= recommendation.category %>-card">
        <div class="btn-reco <%= recommendation.category %>-btn">
            <%= link_to "details",  recommendation_path(recommendation) %>
        </div>
        <div class="<%= recommendation.category %>-icon icons">
            <i class="fa-solid <%= find_icon(recommendation.category)%>"></i>
        </div>
        <div class="recommendation-content">
          <h5><strong><%= recommendation.title %></strong></h5>
          <p><%= recommendation.description.truncate(50) %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/recommendations/edit.html.erb
<div class="container">
  <h1>Edit <%=@recommendation.title%></h1>
  <%= link_to "Back to all the communities", communities_path %>

  <%= render "form"%>
</div>

app/views/recommendations/new.html.erb
<%= link_to "Go back to all the recommendations", community_path(@community) %>

<div class="container">
  <h2>New recommendation</h2>

  <%= render "form"%>
</div>

app/views/recommendations/show.html.erb
<div class="container">
  <%= link_to "Go back to all the recommendations", community_path(@community) %>

  <h1><%= @recommendation.title %></h1>
  <%= @recommendation.category %>
  <%= @recommendation.description %>
  <%= @recommendation.address %>
  <img src="<%=@recommendation.photo%>" alt="photo">

  <%= link_to "Edit", edit_community_recommendation_path(@community, @recommendation) %>
  <%= link_to "Delete", community_recommendation_path(@community, @recommendation), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

  <%= render "ratings/index"%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wr">
  <div class="container nav-flex">
    <div class="nav-brand">
      <%= image_tag "logo.png", alt:"logo", class:"logo_navbar", id:"logo_navbar" %>
      <h3>Would Recommand</h3>
    </div>
    <div class="nav-content">
      <% if user_signed_in? %>
        <%= link_to "My Communities", communities_path %>
        <%= link_to "My Recommendations", communities_path %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <div class="avatar">
          <img src="<%= current_user.avatar%>" alt="profil picture">
        </div>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
        <div class="avatar">
          <img src="https://www.illustre.ch/fp/1770/996/846/1324/sites/default/files/media/field_image/2023-01/brad_pitt_0.jpg" alt="profil picture">
        </div>
      <% end %>

    </div>
  </div>
</div>